// Copyright (c) 2016 Catalin Alexandru Nastase

#pragma once

#include <Platform.h>

#ifdef EDITOR_DLL
#	ifdef EDITOR_EXPORTS
#		define EDITOR_API DLL_EXPORT
#	else
#		define EDITOR_API DLL_IMPORT
#	endif
#	define EDITOR_PRIVATE DLL_PRIVATE
#else
#	define EDITOR_API
#	define EDITOR_PRIVATE
#endif

// disable: "<type> needs to have dll-interface to be used by clients'
// Happens on STL member variables which are not public therefore is ok
#pragma warning(disable : 4251)

// This warns about truncation to 255 characters in debug/browse info
#pragma warning (disable : 4786)

// Turn off warnings generated by long std templates
// This warns about truncation to 255 characters in debug/browse info
#pragma warning (disable : 4503)

#define EDITOR_VERSION "0.0.1"

#define SAFE_DELETE(object_ptr) if(object_ptr != nullptr) { delete object_ptr; object_ptr = nullptr; }
#define SAFE_DELETE_ARRAY(object_ptr) if(object_ptr != nullptr) { delete []object_ptr; object_ptr = nullptr; }
