/* Copyright (c) 2016 Catalin-Alexandru Nastase
*
* Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), 
* to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, 
* sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR
* ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH
* THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE. */

#pragma once

#include <Platform.h>

#include <filesystem>

#ifdef RUNTIME_DLL
#	ifdef RUNTIME_EXPORTS
#		define RUNTIME_API DLL_EXPORT
#		define RUNTIME_TEMPLATE DLL_EXPORT
#	else
#		define RUNTIME_API DLL_IMPORT
#		define RUNTIME_TEMPLATE
#	endif
#	define RUNTIME_PRIVATE DLL_PRIVATE
#else
#	define RUNTIME_API
#	define RUNTIME_TEMPLATE
#	define RUNTIME_PRIVATE
#endif

// disable: "<type> needs to have dll-interface to be used by clients'
// Happens on STL member variables which are not public therefore is ok
#ifdef _MSC_VER
#pragma warning(disable : 4251)

// This warns about truncation to 255 characters in debug/browse info
#pragma warning (disable : 4786)

// Turn off warnings generated by long std templates
// This warns about truncation to 255 characters in debug/browse info
#pragma warning (disable : 4503)
#endif

#define RUNTIME_VERSION "0.0.1"

#define ENGINE_UNIT_M 1

#define MAX_PATH_SIZE 255

#define __STRINGIFY(x) #x
#define STRINGIFY(x) __STRINGIFY(x)

#ifdef _MSC_VER
#define __MESSAGE(text) __pragma( message(__FILE__ "(" STRINGIFY(__LINE__) ")" text) )
#else
#define __MESSAGE(text)
#endif

// Outputs a warning during compile time
#define ENGINE_WARNING(text) __MESSAGE( " : Warning: " ##text )

// Outputs an error during compile time
#define ENGINE_ERROR(text) __MESSAGE( " : Error: " ##text )

// Outputs a message during compile time
#define ENGINE_MESSAGE(text) __MESSAGE( ": " ##text )

#define ENGINE_TODO(text) __MESSAGE( ": TODO: " ##text )

namespace filesystem = std::filesystem;
